# Generated by Django 3.0.8 on 2020-07-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0002_auto_20200719_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jop.Category'),
            preserve_default=False,
        ),
    ]
